# Generated by Django 5.0.7 on 2024-08-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_marca_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='productos', to='producto.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
