# Generated by Django 5.0.7 on 2024-08-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_producto_categoria_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_otro',
            field=models.FloatField(blank=True, default=0, help_text='Precio para otro tipo de pago', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_tarjeta',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
