# Generated by Django 5.0.7 on 2024-08-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
