# Generated by Django 5.0.7 on 2024-08-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_servicio_imagen_alter_servicio_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.TextField(),
        ),
    ]
