# Generated by Django 5.0.7 on 2024-08-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor_nombre',
            field=models.CharField(default='Nombre por defecto', max_length=100),
        ),
    ]
