# Generated by Django 5.0.7 on 2024-08-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_autor_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor_nombre',
            new_name='autor_name',
        ),
    ]
