# Generated by Django 5.0.7 on 2024-08-13 05:13

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_contenido_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.custom_upload_to_blog),
        ),
    ]
